analytics: {}
color:
  brandColors:
    - '#E0C8D0'
    - '#602028'
    - '#A07080'
    - '#B04040'
    - '#000000'
  brandStrength: 0
  lightness: 0.1875
  rhythmicContrast: 0.75
  saturation: 0.6875
cta: {}
layout_spectrum: 1
name: Ricky Simmons
opengraph: {}
purpose: []
typography_spectrum: 0.87494
